name: Build PDF from LaTeX

on:
  release:
    types: [created, published, edited, prereleased]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile Latex
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          main.tex
          model.tex
        latexmk_use_xelatex: true
        latexmk_shell_escape: true   

    - name: Upload Book to release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: book
        path: main.pdf
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/pdf # Optional

    - name: Upload Model to release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: book
        path: model.pdf
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/pdf # Optional
